### ISSUE TITLE
Add helpers and examples for usage with Floki

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/test_selector#15]
We should mention we're also supporting [Floki](https://github.com/philss/floki) out of the box:

```ex
html
|> Floki.find("[test-selector=#{SomeView.test_selector("user")}")
|> Floki.attribute("test-value")
```

```ex
{:safe, selector} = IndexView.test()
Floki.find(html, "[#{selector}]")
```

And we might want to rename `TestSelector.Test.Helpers` to `TestSelector.Hound.Helpers`, and optionally add `TestSelector.Floki.Helpers` (if any).

**Comment by fatboypunk** [comment]
Fixed in #22
